public static partial class ModTranslate
{
	// Bảng từ điển dịch chuỗi hệ thống (290 cụm từ, sắp xếp theo độ dài giảm dần)
	public static readonly string[][] WordTranslations = new string[][]
	{
		new string[] { "Anda masuk ke terlalu banyak akun di perangkat yang sama.[1]", "Bạn đã đăng nhập quá nhiều tài khoản trên cùng một thiết bị. [1]" },
		new string[] { "Anda masuk ke terlalu banyak akun di perangkat yang sama", "Bạn đã đăng nhập quá nhiều tài khoản trên cùng một thiết bị" },
		new string[] { "Too many accounts logged in on the same device", "Bạn đã đăng nhập quá nhiều tài khoản trên cùng một thiết bị" },
		new string[] { "terlalu banyak akun di perangkat yang sama", "quá nhiều tài khoản trên cùng một thiết bị" },
		new string[] { "Anda belum bisa memakai item ini", "Bạn chưa thể dùng vật phẩm này" },
		new string[] { "Anda chưa thể dùng vật phẩm này", "Bạn chưa thể dùng vật phẩm này" },
		new string[] { "Error, harap coba lagi.[500]", "Lỗi kết nối máy chủ, vui lòng thử lại sau. [500]" },
		new string[] { "Tidak bisa memakai item ini", "Không thể dùng vật phẩm này" },
		new string[] { "Server sedang pemeliharaan", "Máy chủ đang bảo trì" },
		new string[] { "Tidak bisa diperdagangkan", "Không thể giao dịch" },
		new string[] { "You cannot use this item", "Bạn chưa thể dùng vật phẩm này" },
		new string[] { "Error, harap coba lagi", "Lỗi kết nối máy chủ, vui lòng thử lại sau" },
		new string[] { "Account does not exist", "Tài khoản không tồn tại" },
		new string[] { "Karakter sedang sibuk", "Nhân vật đang bận" },
		new string[] { "Tidak dapat terhubung", "Không thể kết nối máy chủ" },
		new string[] { "Akun sedang digunakan", "Tài khoản đang đăng nhập" },
		new string[] { "Kekuatan tidak cukup", "Sức mạnh không đủ" },
		new string[] { "Akun tidak terdaftar", "Tài khoản chưa đăng ký" },
		new string[] { "Account is logged in", "Tài khoản đang đăng nhập" },
		new string[] { "Cannot use this item", "Không thể dùng vật phẩm này" },
		new string[] { "terlalu banyak akun", "quá nhiều tài khoản" },
		new string[] { "perangkat yang sama", "cùng một thiết bị" },
		new string[] { "Anda telah menerima", "Bạn đã nhận được" },
		new string[] { "Tidak cukup permata", "Không đủ ngọc" },
		new string[] { "Tingkat tidak cukup", "Cấp độ không đủ" },
		new string[] { "Server đang bảo trì", "Máy chủ đang bảo trì" },
		new string[] { "Sedang pemeliharaan", "Máy chủ đang bảo trì" },
		new string[] { "Server sedang penuh", "Máy chủ đã đầy" },
		new string[] { "Tidak dapat ditukar", "Không thể giao dịch" },
		new string[] { "Permintaan kekuatan", "Yêu cầu sức mạnh" },
		new string[] { "Kekuatan dibutuhkan", "Yêu cầu sức mạnh" },
		new string[] { "Power is not enough", "Sức mạnh không đủ" },
		new string[] { "Level is not enough", "Cấp độ không đủ" },
		new string[] { "harap coba kembali", "vui lòng thử lại" },
		new string[] { "Sedang maintenance", "Máy chủ đang bảo trì" },
		new string[] { "Pembelian berhasil", "Mua thành công" },
		new string[] { "Penjualan berhasil", "Bán thành công" },
		new string[] { "Server maintenance", "Máy chủ đang bảo trì" },
		new string[] { "silakan coba lagi", "vui lòng thử lại" },
		new string[] { "silahkan coba lại", "vui lòng thử lại" },
		new string[] { "Kekuatan không đủ", "Sức mạnh không đủ" },
		new string[] { "Level tidak cukup", "Cấp độ không đủ" },
		new string[] { "Akun sedang login", "Tài khoản đang đăng nhập" },
		new string[] { "You have received", "Bạn đã nhận được" },
		new string[] { "Character is busy", "Nhân vật đang bận" },
		new string[] { "Connection failed", "Kết nối thất bại" },
		new string[] { "Inventory is full", "Hành trang đã đầy" },
		new string[] { "Sell successfully", "Bán thành công" },
		new string[] { "Power requirement", "Yêu cầu sức mạnh" },
		new string[] { "Anda mendapatkan", "Bạn nhận được" },
		new string[] { "Tidak cukup emas", "Không đủ vàng" },
		new string[] { "Tidak đủ permata", "Không đủ ngọc" },
		new string[] { "Koneksi terputus", "Mất kết nối máy chủ" },
		new string[] { "Kata sandi salah", "Sai mật khẩu" },
		new string[] { "Membeli berhasil", "Mua thành công" },
		new string[] { "Menjual berhasil", "Bán thành công" },
		new string[] { "Buy successfully", "Mua thành công" },
		new string[] { "harap coba lagi", "vui lòng thử lại" },
		new string[] { "Gagal terhubung", "Không thể kết nối máy chủ" },
		new string[] { "Server đang đầy", "Máy chủ đã đầy" },
		new string[] { "Not enough gold", "Không đủ vàng" },
		new string[] { "Not enough gems", "Không đủ ngọc" },
		new string[] { "Connection lost", "Mất kết nối máy chủ" },
		new string[] { "Level tidak đủ", "Cấp độ không đủ" },
		new string[] { "Level không đủ", "Cấp độ không đủ" },
		new string[] { "Password salah", "Sai mật khẩu" },
		new string[] { "Akun tidak ada", "Tài khoản không tồn tại" },
		new string[] { "Not enough gem", "Không đủ ngọc" },
		new string[] { "Wrong password", "Sai mật khẩu" },
		new string[] { "Server is full", "Máy chủ đã đầy" },
		new string[] { "Anda menerima", "Bạn nhận được" },
		new string[] { "Không đủ ngọc", "Không đủ ngọc" },
		new string[] { "Koneksi gagal", "Kết nối thất bại" },
		new string[] { "Kekuatan Anda", "Sức mạnh của bạn" },
		new string[] { "Sarung Tangan", "Găng tay" },
		new string[] { "Chest is full", "Rương đồ đã đầy" },
		new string[] { "Require power", "Yêu cầu sức mạnh" },
		new string[] { "Keberuntungan", "May Mắn" },
		new string[] { "Server penuh", "Máy chủ đã đầy" },
		new string[] { "Ransel penuh", "Hành trang đã đầy" },
		new string[] { "Waktu tunggu", "Thời gian chờ" },
		new string[] { "Masa berlaku", "Hạn sử dụng" },
		new string[] { "Kacang Ajaib", "Đậu thần" },
		new string[] { "Meningkatkan", "Tăng" },
		new string[] { "You received", "Bạn nhận được" },
		new string[] { "Login failed", "Đăng nhập thất bại" },
		new string[] { "Sell success", "Bán thành công" },
		new string[] { "Cannot trade", "Không thể giao dịch" },
		new string[] { "Tidak cukup", "Không đủ" },
		new string[] { "Gagal masuk", "Đăng nhập thất bại" },
		new string[] { "Kotak penuh", "Rương đồ đã đầy" },
		new string[] { "Kedaluwarsa", "Hạn sử dụng" },
		new string[] { "Pohon Ajaib", "Cây Đậu Thần" },
		new string[] { "Memantulkan", "Phản" },
		new string[] { "Bag is full", "Hành trang đã đầy" },
		new string[] { "Box is full", "Rương đồ đã đầy" },
		new string[] { "Buy success", "Mua thành công" },
		new string[] { "Requirement", "Yêu cầu" },
		new string[] { "Dragon Ball", "Ngọc Rồng" },
		new string[] { "Dibutuhkan", "Yêu cầu" },
		new string[] { "Pertahanan", "Giáp" },
		new string[] { "Menghindar", "Né đòn" },
		new string[] { "Mengurangi", "Giảm" },
		new string[] { "Not enough", "Không đủ" },
		new string[] { "Untradable", "Không thể giao dịch" },
		new string[] { "Expires in", "Hạn sử dụng" },
		new string[] { "Your power", "Sức mạnh của bạn" },
		new string[] { "Senzu Bean", "Đậu thần" },
		new string[] { "Magic Bean", "Đậu thần" },
		new string[] { "Magic Tree", "Cây Đậu Thần" },
		new string[] { "Penyamaran", "Cải trang" },
		new string[] { "Tahun Baru", "Năm Mới" },
		new string[] { "Peliharaan", "Thú cưng" },
		new string[] { "Penghancur", "Hủy Diệt" },
		new string[] { "Kemenangan", "Chiến Thắng" },
		new string[] { "Masa depan", "Tương lai" },
		new string[] { "coba lagi", "thử lại" },
		new string[] { "Tas penuh", "Hành trang đã đầy" },
		new string[] { "Rương đầy", "Rương đồ đã đầy" },
		new string[] { "Bola Naga", "Ngọc Rồng" },
		new string[] { "Kecepatan", "Tốc độ" },
		new string[] { "Kerusakan", "Sát thương" },
		new string[] { "Wait time", "Thời gian chờ" },
		new string[] { "Peristiwa", "Sự kiện" },
		new string[] { "Kemampuan", "Kỹ năng" },
		new string[] { "Misterius", "Bí Ẩn" },
		new string[] { "Kura-kura", "Rùa" },
		new string[] { "Tengkorak", "Đầu Lâu" },
		new string[] { "Masa Lalu", "Quá khứ" },
		new string[] { "Terkunci", "Đã khóa" },
		new string[] { "Berhasil", "Thành công" },
		new string[] { "Serangan", "Sức đánh" },
		new string[] { "Kritikal", "Chí mạng" },
		new string[] { "Menyerap", "Hút" },
		new string[] { "Pulihkan", "Hồi phục" },
		new string[] { "Trousers", "Quần" },
		new string[] { "Critical", "Chí mạng" },
		new string[] { "Increase", "Tăng" },
		new string[] { "Menyamar", "Cải trang" },
		new string[] { "Disguise", "Cải trang" },
		new string[] { "Malaikat", "Thiên Sứ" },
		new string[] { "Kacamata", "Kính" },
		new string[] { "Realitas", "Thực Tại" },
		new string[] { "Kekuatan", "Sức Mạnh" },
		new string[] { "Pahlawan", "Anh Hùng" },
		new string[] { "Serigala", "Sói" },
		new string[] { "Turnamen", "Đại hội võ thuật" },
		new string[] { "Permata", "Ngọc" },
		new string[] { "Expired", "Hết hạn" },
		new string[] { "Diamond", "Ngọc" },
		new string[] { "Success", "Thành công" },
		new string[] { "Defense", "Giáp" },
		new string[] { "Reflect", "Phản" },
		new string[] { "Recover", "Hồi phục" },
		new string[] { "seconds", "giây" },
		new string[] { "Bendera", "Cờ" },
		new string[] { "Bintang", "Sao" },
		new string[] { "Tongkat", "Gậy" },
		new string[] { "Glasses", "Kính" },
		new string[] { "Legenda", "Huyền Thoại" },
		new string[] { "Spesial", "Đặc Biệt" },
		new string[] { "Terbang", "Bay" },
		new string[] { "Kelinci", "Thỏ" },
		new string[] { "Beruang", "Gấu" },
		new string[] { "Kristal", "Pha Lê" },
		new string[] { "Berlian", "Kim Cương" },
		new string[] { "Aprikot", "Hoa Mai" },
		new string[] { "Cokelat", "Socola" },
		new string[] { "Sarung", "Găng tay" },
		new string[] { "Celana", "Quần" },
		new string[] { "Sepatu", "Giày" },
		new string[] { "Kacang", "Đậu thần" },
		new string[] { "Kapsul", "Capsule" },
		new string[] { "Rambut", "Tóc" },
		new string[] { "Tenaga", "KI" },
		new string[] { "setiap", "mỗi" },
		new string[] { "Locked", "Đã khóa" },
		new string[] { "Gloves", "Găng tay" },
		new string[] { "Failed", "Thất bại" },
		new string[] { "Damage", "Sát thương" },
		new string[] { "Attack", "Sức đánh" },
		new string[] { "Absorb", "Hút" },
		new string[] { "Reduce", "Giảm" },
		new string[] { "second", "giây" },
		new string[] { "Avatar", "Cải trang" },
		new string[] { "Cincin", "Nhẫn" },
		new string[] { "Hadiah", "Quà" },
		new string[] { "Kostum", "Trang phục" },
		new string[] { "Kuning", "Vàng" },
		new string[] { "Dragon", "Rồng" },
		new string[] { "Pedang", "Kiếm" },
		new string[] { "Topeng", "Mặt nạ" },
		new string[] { "Daging", "Thịt" },
		new string[] { "Khusus", "Đặc Biệt" },
		new string[] { "Kucing", "Mèo" },
		new string[] { "Anjing", "Chó" },
		new string[] { "Monyet", "Khỉ" },
		new string[] { "Burung", "Chim" },
		new string[] { "Tulang", "Xương" },
		new string[] { "Sakura", "Hoa Anh Đào" },
		new string[] { "Persik", "Hoa Đào" },
		new string[] { "Coklat", "Socola" },
		new string[] { "Permen", "Kẹo" },
		new string[] { "Perang", "Chiến tranh" },
		new string[] { "Radar", "Rada" },
		new string[] { "Jubah", "Áo choàng" },
		new string[] { "Gagal", "Thất bại" },
		new string[] { "Kunci", "Khóa" },
		new string[] { "Darah", "HP" },
		new string[] { "detik", "giây" },
		new string[] { "Glove", "Găng tay" },
		new string[] { "Shirt", "Áo" },
		new string[] { "Armor", "Áo" },
		new string[] { "Pants", "Quần" },
		new string[] { "Shoes", "Giày" },
		new string[] { "Boots", "Giày" },
		new string[] { "Cloak", "Áo choàng" },
		new string[] { "Stone", "Đá" },
		new string[] { "Speed", "Tốc độ" },
		new string[] { "Dodge", "Né đòn" },
		new string[] { "every", "mỗi" },
		new string[] { "Kotak", "Hộp" },
		new string[] { "Kartu", "Thẻ" },
		new string[] { "Tahun", "Năm" },
		new string[] { "Hitam", "Đen" },
		new string[] { "Merah", "Đỏ" },
		new string[] { "Hijau", "Xanh lá" },
		new string[] { "Putih", "Trắng" },
		new string[] { "Bulan", "Mặt trăng" },
		new string[] { "Sayap", "Cánh" },
		new string[] { "Sword", "Kiếm" },
		new string[] { "Stick", "Gậy" },
		new string[] { "Acara", "Sự kiện" },
		new string[] { "Ajaib", "Thần bí" },
		new string[] { "Bakar", "Nướng" },
		new string[] { "Petir", "Sấm sét" },
		new string[] { "Ruang", "Không Gian" },
		new string[] { "Waktu", "Thời Gian" },
		new string[] { "Super", "Siêu" },
		new string[] { "Papan", "Ván" },
		new string[] { "Iblis", "Quỷ" },
		new string[] { "Setan", "Ma quỷ" },
		new string[] { "Bunga", "Hoa" },
		new string[] { "Mawar", "Hoa Hồng" },
		new string[] { "Pohon", "Cây" },
		new string[] { "Benih", "Hạt giống" },
		new string[] { "Paket", "Gói" },
		new string[] { "Murid", "Đệ tử" },
		new string[] { "Teman", "Bạn bè" },
		new string[] { "Juara", "Vô địch" },
		new string[] { "Piala", "Cúp" },
		new string[] { "Dunia", "Thế giới" },
		new string[] { "Batu", "Đá" },
		new string[] { "Baju", "Áo" },
		new string[] { "Topi", "Nón" },
		new string[] { "Emas", "Vàng" },
		new string[] { "Koin", "Xu" },
		new string[] { "hari", "ngày" },
		new string[] { "Ruby", "Hồng ngọc" },
		new string[] { "Gold", "Vàng" },
		new string[] { "Coin", "Xu" },
		new string[] { "days", "ngày" },
		new string[] { "Peti", "Rương" },
		new string[] { "Dewa", "Thần Linh" },
		new string[] { "Biru", "Xanh dương" },
		new string[] { "Naga", "Rồng" },
		new string[] { "Bola", "Ngọc" },
		new string[] { "Ball", "Ngọc" },
		new string[] { "Wing", "Cánh" },
		new string[] { "Mask", "Mặt nạ" },
		new string[] { "Paha", "Đùi" },
		new string[] { "Ayam", "Gà" },
		new string[] { "Babi", "Heo" },
		new string[] { "Ikan", "Cá" },
		new string[] { "Susu", "Sữa" },
		new string[] { "Kopi", "Cà phê" },
		new string[] { "Bumi", "Trái Đất" },
		new string[] { "Jiwa", "Linh Hồn" },
		new string[] { "Awan", "Mây" },
		new string[] { "Hati", "Trái Tim" },
		new string[] { "Daun", "Lá" },
		new string[] { "Buah", "Quả" },
		new string[] { "Guru", "Sư phụ" },
		new string[] { "Klan", "Bang hội" },
		new string[] { "Clan", "Bang hội" },
		new string[] { "Kue", "Bánh" },
		new string[] { "Teh", "Trà" },
		new string[] { "Air", "Nước" },
		new string[] { "Api", "Lửa" },
		new string[] { "Es", "Băng" },
	};
}
